apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsocket-consumer
    template: application-template-stibuild
  name: rsocket-consumer
spec:
  clusterIP: None
  ports:
    - name: rsocket-consumer
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: rsocket-consumer
  sessionAffinity: None
  type: ClusterIP
