apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsocket-producer
    template: application-template-stibuild
  name: rsocket-producer
spec:
  clusterIP: None
  ports:
    - name: rsocket-producer
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: rsocket
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    name: rsocket-producer
  sessionAffinity: None
  type: ClusterIP
